

server:
  port: 9999
spring:
  profiles:
    active: dev
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id : consumer-service
          uri : lb://consumer-service
          predicates:
          - Path=/consumer/**
          filters:
          - StripPrefix=1
        - id: provider-service
          uri: lb://provider-service
          predicates:
          - Path=/provider/**
          filters:
          - StripPrefix=1
# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 6000
  shareSecurityContext: true


# 注册中心
eureka:
  instance:
    #prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:10025/eureka/


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
