spring:
  application:
    name: eureka-server

server:
  port: 8070

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8070/eureka/

